### ISSUE TITLE
NOT AN ISSUE

### ISSUE THREAD

**Issue by Crewxx** [ItayRosen/LinkedIn-Mass-Connect#2]
Hi,

Great tool, please just want to find out if there is actually a way to tweak the script to bypass LNKD "You’re out of invitations for now" message. Each time the message warning comes up, the invite don't get sent anymore. 

Anyway to bypass this and continuing sending the invitations?

Thanks

**Comment by etairl** [comment]
The limitation is per account. I'm not aware of a method to bypass it.

**Comment by Crewxx** [comment]
Alright, thanks for the feedback.
